version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "npm"
    # Set version updating strategy
    versioning-strategy: auto
    # Limit the number of open pull requests
    open-pull-requests-limit: 5
    # Configure automatic merge of minor and patch updates
    commit-message:
      prefix: "chore"
      include: "scope"
    # Allow up to 10 pull requests for dependencies
    pull-request-branch-name:
      separator: "-"
    # Group dependencies updates when possible
    groups:
      development-dependencies:
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "*test*"
          - "*jest*"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*eslint*"
          - "*prettier*"
          - "*test*"
          - "*jest*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
