name: Dependabot Security Updates

on:
  workflow_dispatch:
  schedule:
    # Run security audit weekly
    - cron: '0 0 * * 0'

permissions:
  contents: read
  issues: write

jobs:
  security-audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit

      # Run npm audit fix if you want to automatically fix vulnerabilities
      # This is optional and might cause breaking changes, so use with caution
      - name: Fix vulnerabilities (if possible)
        run: npm audit fix
        continue-on-error: true

      # Create issues for any vulnerabilities that can't be fixed automatically
      - name: Create issues for vulnerabilities
        if: failure()
        run: |
          gh issue create \
            --title "Security Vulnerability Found in Dependencies" \
            --label "security,dependencies" \
            --body "## Security Vulnerabilities

          A security audit has found potential vulnerabilities in the project dependencies.

          ### Action Required

          Please run \`npm audit\` to see the details of the vulnerabilities and then run \`npm audit fix\` to automatically fix issues that don't require major version updates.

          For vulnerabilities that require manual intervention:

          1. Review the vulnerability details
          2. Update the affected packages manually
          3. Test thoroughly after updates
          4. Close this issue once resolved

          ### Vulnerability Details

          Run \`npm audit\` locally for more information about the specific vulnerabilities."
        env:
          GH_TOKEN: ${{ github.token }}
